---
n_epochs: 200
batch_size: 256
lr: 0.0002
n_cpu: 8
latent_dim: 100
img_size: 64
img_channels: 3
n_critic: 3
sample_interval: 1000
gen_weight_path: "ModelWeights/Gen/"
disc_weight_path: "ModelWeights/Disc/"
image_save_path: "Generated Images/"
datafolder_path: "Data"
load_last_checkpoint: false
wdiv_p_value: 6
wdiv_k_value: 2